# Generated by Django 5.1.2 on 2024-10-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='location',
            new_name='linked_in',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='description',
        ),
        migrations.CreateModel(
            name='WorkDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('work', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cv.workexperience')),
            ],
        ),
    ]
