# Generated by Django 5.1.2 on 2024-10-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_rename_location_workexperience_linked_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('intern', 'Intern'), ('contract', 'Contract')], default='full-time', max_length=50),
        ),
    ]
